# -*- coding: utf-8 -*-
"""Day_20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mEN847acm6IWkJiiQzUe4znjx-erOccY
"""

# CORPORATE MARKET RESEARCH & STRATEGY

from openai import OpenAI
import json
import re
import asyncio
from google.colab import userdata
api_key=userdata.get('gapi')

# ================================
# GROQ CLIENT SETUP
# ================================
client = OpenAI(
    api_key=api_key,
    base_url="https://api.groq.com/openai/v1"
)

# ================================
# SAFE JSON PARSER
# ================================
def safe_json_parse(text):
    try:
        return json.loads(text)
    except:
        match = re.search(r"\{.*\}|\[.*\]", text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group())
            except:
                pass
    return {"error": "Invalid JSON", "raw": text}


# ================================
# LLM HELPER
# ================================
def call_llm(system_prompt, user_message):
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        temperature=0,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_message}
        ]
    )
    return response.choices[0].message.content.strip()

# ================================
# WORKER AGENTS (ALL FIXED)
# ================================

def market_research_worker(goal):
    print("\n  [Market Research Worker] Collecting data...")
    reply = call_llm(
        system_prompt="""
        Return ONLY valid JSON:
        {
          "demand_level": "High/Medium/Low",
          "target_cities": ["city1","city2","city3"],
          "competition_level": "High/Moderate/Low",
          "summary": "string"
        }
        """,
        user_message=goal
    )
    return safe_json_parse(reply)


def finance_worker(goal):
    print("\n  [Finance Worker] Analyzing budget & ROI...")
    reply = call_llm(
        system_prompt="""
        Return ONLY valid JSON:
        {
          "estimated_investment_usd": 1000000,
          "projected_roi_years": 3,
          "risk_level": "Low/Medium/High",
          "summary": "string"
        }
        """,
        user_message=goal
    )
    return safe_json_parse(reply)


def operations_worker(goal):
    print("\n  [Operations Worker] Evaluating supply chain...")
    reply = call_llm(
        system_prompt="""
        Return ONLY valid JSON:
        {
          "factory_scalability": "High/Medium/Low",
          "shipping_bottleneck": true,
          "bottleneck_reason": "string",
          "summary": "string"
        }
        """,
        user_message=goal
    )
    return safe_json_parse(reply)


def legal_worker(goal):
    print("\n  [Legal Worker] Reviewing regulations...")
    reply = call_llm(
        system_prompt="""
        Return ONLY valid JSON:
        {
          "trademark_available": true,
          "import_certification_required": false,
          "certification_name": "string",
          "summary": "string"
        }
        """,
        user_message=goal
    )
    return safe_json_parse(reply)


def hr_worker(goal):
    print("\n  [HR Worker] Assessing staffing needs...")
    reply = call_llm(
        system_prompt="""
        Return ONLY valid JSON:
        {
          "new_hires_required": 50,
          "roles": {"engineer": 20, "sales": 30},
          "summary": "string"
        }
        """,
        user_message=goal
    )
    return safe_json_parse(reply)


# ================================
# MANAGER AGENT (FIXED)
# ================================
def manager_agent(goal):
    print("\n[Manager Agent] Analyzing goal...")
    print(f"  Goal: {goal}\n")

    reply = call_llm(
        system_prompt="""
        Return ONLY JSON list:
        ["market_research", "finance", "operations", "legal", "hr"]
        """,
        user_message=goal
    )

    tasks = safe_json_parse(reply)
    print(f"  Tasks Assigned: {[t.replace('_', ' ').title() for t in tasks]}")
    return tasks


# ================================
# FINAL DECISION (UNCHANGED)
# ================================
def make_final_decision(results):
    score, flags, positives = 0, [], []

    mr  = results.get("market_research", {})
    fin = results.get("finance", {})
    ops = results.get("operations", {})
    leg = results.get("legal", {})
    hr  = results.get("hr", {})

    if mr.get("demand_level") == "High":
        score += 1; positives.append("Strong demand")

    if fin.get("projected_roi_years", 99) <= 3:
        score += 1; positives.append("Good ROI")

    if ops.get("factory_scalability") == "High":
        score += 1; positives.append("Scalable operations")

    if leg.get("trademark_available"):
        score += 1; positives.append("Trademark available")

    if hr.get("new_hires_required", 999) <= 100:
        score += 1; positives.append("Manageable hiring")

    if ops.get("shipping_bottleneck"):
        flags.append("Shipping bottleneck")

    if leg.get("import_certification_required"):
        flags.append("Certification needed")

    if fin.get("risk_level") == "High":
        flags.append("High financial risk")

    pct = (score / 5) * 100
    verdict = "PROCEED" if pct >= 75 else "CONDITIONAL" if pct >= 50 else "NOT RECOMMENDED"

    return {"score": f"{pct:.0f}%", "verdict": verdict, "positives": positives, "flags": flags}


# ================================
# MAIN SYSTEM
# ================================
def run_system(goal):
    print("  CORPORATE MARKET RESEARCH & STRATEGY SYSTEM")

    tasks = manager_agent(goal)
    results = {}

    worker_map = {
        "market_research": market_research_worker,
        "finance": finance_worker,
        "operations": operations_worker,
        "legal": legal_worker,
        "hr": hr_worker
    }

    for task in tasks:
        if task in worker_map:
            results[task] = worker_map[task](goal)

    print("\n  WORKER REPORTS")
    for agent, data in results.items():
        print(f"\n  📌 {agent.replace('_', ' ').title()}")
        print(f"     → {data.get('summary', 'No summary')}")

    decision = make_final_decision(results)

    print("\n  FINAL DECISION")
    print(f"  Score: {decision['score']} | Verdict: {decision['verdict']}")

    return decision


# RUN
run_system("Evaluate feasibility of launching Product Y in Asia.")

# CORPORATE MARKET RESEARCH & STRATEGY
# Agent 1: Crisis Coordinator (Broadcaster)
# - Broadcasts: “Data breach detected in customer database. Immediate response required.”
# - Sends this to all other agents simultaneously.

# 🛡️ Agent 2: IT Security Agent
# - Receives broadcast.
# - Responds: “Isolate affected servers, patch vulnerabilities, start forensic analysis.”

# 📞 Agent 3: Communications Agent
# - Receives broadcast.
# - Responds: “Draft internal memo, prepare press release, notify stakeholders.”

# 💰 Agent 4: Finance Agent
# - Receives broadcast.
# - Responds: “Estimate financial impact, allocate emergency funds, review insurance coverage.”

# 👩‍⚖️ Agent 5: Legal Agent
# - Receives broadcast.
# - Responds: “Assess regulatory obligations, prepare compliance reports, advise on liability.”

# 👩‍💼 Agent 6: HR Agent
# - Receives broadcast.
# - Responds: “Brief employees, provide guidance on handling customer queries, ensure morale support.”

# 🧑‍⚖️ Agent 7: Decision Agent (Coordinator)
# - Collects all responses.
# - Integrates into a final crisis response plan:
# “Servers isolated, communications prepared, financial impact assessed, compliance secured, employees briefed.”

from openai import OpenAI
import json
import re
import asyncio
from google.colab import userdata
api_key=userdata.get('gapi')

# ================================
# GROQ CLIENT SETUP
# ================================
client = OpenAI(
    api_key=api_key,
    base_url="https://api.groq.com/openai/v1"
)

# ================================
# SAFE JSON PARSER
# ================================
def safe_json_parse(text):
    try:
        return json.loads(text)
    except:
        match = re.search(r"\{.*\}|\[.*\]", text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group())
            except:
                pass
    return {"error": "Invalid JSON", "raw": text}


# ================================
# LLM HELPER
# ================================
def call_llm(system_prompt, user_message):
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        temperature=0,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_message}
        ]
    )
    return response.choices[0].message.content.strip()

# ================================
# WORKER AGENTS (ALL FIXED)
# ================================

def market_research_worker(goal):
    print("\n  [Market Research Worker] Collecting data...")
    reply = call_llm(
        system_prompt="""
        Return ONLY valid JSON:
        {
          "demand_level": "High/Medium/Low",
          "target_cities": ["city1","city2","city3"],
          "competition_level": "High/Moderate/Low",
          "summary": "string"
        }
        """,
        user_message=goal
    )
    return safe_json_parse(reply)


def finance_worker(goal):
    print("\n  [Finance Worker] Analyzing budget & ROI...")
    reply = call_llm(
        system_prompt="""
        Return ONLY valid JSON:
        {
          "estimated_investment_usd": 1000000,
          "projected_roi_years": 3,
          "risk_level": "Low/Medium/High",
          "summary": "string"
        }
        """,
        user_message=goal
    )
    return safe_json_parse(reply)


def operations_worker(goal):
    print("\n  [Operations Worker] Evaluating supply chain...")
    reply = call_llm(
        system_prompt="""
        Return ONLY valid JSON:
        {
          "factory_scalability": "High/Medium/Low",
          "shipping_bottleneck": true,
          "bottleneck_reason": "string",
          "summary": "string"
        }
        """,
        user_message=goal
    )
    return safe_json_parse(reply)


def legal_worker(goal):
    print("\n  [Legal Worker] Reviewing regulations...")
    reply = call_llm(
        system_prompt="""
        Return ONLY valid JSON:
        {
          "trademark_available": true,
          "import_certification_required": false,
          "certification_name": "string",
          "summary": "string"
        }
        """,
        user_message=goal
    )
    return safe_json_parse(reply)


def hr_worker(goal):
    print("\n  [HR Worker] Assessing staffing needs...")
    reply = call_llm(
        system_prompt="""
        Return ONLY valid JSON:
        {
          "new_hires_required": 50,
          "roles": {"engineer": 20, "sales": 30},
          "summary": "string"
        }
        """,
        user_message=goal
    )
    return safe_json_parse(reply)


# ================================
# MANAGER AGENT (FIXED)
# ================================
def manager_agent(goal):
    print("\n[Manager Agent] Analyzing goal...")
    print(f"  Goal: {goal}\n")

    reply = call_llm(
        system_prompt="""
        Return ONLY JSON list:
        ["market_research", "finance", "operations", "legal", "hr"]
        """,
        user_message=goal
    )

    tasks = safe_json_parse(reply)
    print(f"  Tasks Assigned: {[t.replace('_', ' ').title() for t in tasks]}")
    return tasks


# ================================
# FINAL DECISION (UNCHANGED)
# ================================
def make_final_decision(results):
    score, flags, positives = 0, [], []

    mr  = results.get("market_research", {})
    fin = results.get("finance", {})
    ops = results.get("operations", {})
    leg = results.get("legal", {})
    hr  = results.get("hr", {})

    if mr.get("demand_level") == "High":
        score += 1; positives.append("Strong demand")

    if fin.get("projected_roi_years", 99) <= 3:
        score += 1; positives.append("Good ROI")

    if ops.get("factory_scalability") == "High":
        score += 1; positives.append("Scalable operations")

    if leg.get("trademark_available"):
        score += 1; positives.append("Trademark available")

    if hr.get("new_hires_required", 999) <= 100:
        score += 1; positives.append("Manageable hiring")

    if ops.get("shipping_bottleneck"):
        flags.append("Shipping bottleneck")

    if leg.get("import_certification_required"):
        flags.append("Certification needed")

    if fin.get("risk_level") == "High":
        flags.append("High financial risk")

    pct = (score / 5) * 100
    verdict = "PROCEED" if pct >= 75 else "CONDITIONAL" if pct >= 50 else "NOT RECOMMENDED"

    return {"score": f"{pct:.0f}%", "verdict": verdict, "positives": positives, "flags": flags}


# ================================
# MAIN SYSTEM
# ================================
def run_system(goal):
    print("  CORPORATE MARKET RESEARCH & STRATEGY SYSTEM")

    tasks = manager_agent(goal)
    results = {}

    worker_map = {
        "market_research": market_research_worker,
        "finance": finance_worker,
        "operations": operations_worker,
        "legal": legal_worker,
        "hr": hr_worker
    }

    for task in tasks:
        if task in worker_map:
            results[task] = worker_map[task](goal)

    print("\n  WORKER REPORTS")
    for agent, data in results.items():
        print(f"\n  📌 {agent.replace('_', ' ').title()}")
        print(f"     → {data.get('summary', 'No summary')}")

    decision = make_final_decision(results)

    print("\n  FINAL DECISION")
    print(f"  Score: {decision['score']} | Verdict: {decision['verdict']}")

    return decision


# RUN
run_system("Evaluate feasibility of launching Product Y in Asia.")

from openai import OpenAI
import json
import re
import asyncio
from google.colab import userdata
api_key=userdata.get('gapi')

# ================================
# GROQ CLIENT SETUP
# ================================
client = OpenAI(
    api_key=api_key,
    base_url="https://api.groq.com/openai/v1"
)

# ================================
# SAFE JSON PARSER
# ================================
def safe_json_parse(text):
    try:
        return json.loads(text)
    except:
        match = re.search(r"\{.*\}|\[.*\]", text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group())
            except:
                pass
    return {"error": "Invalid JSON", "raw": text}


# ================================
# LLM HELPER
# ================================
def call_llm(system_prompt, user_message):
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        temperature=0,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_message}
        ]
    )
    return response.choices[0].message.content.strip()


# ================================
# AGENTS (ASYNC FOR PARALLEL EXECUTION)
# ================================

async def marketing_agent(goal):
    print("\n📈 Marketing Agent working...")
    reply = call_llm(
        """Return ONLY JSON:
        {
          "campaigns": ["string"],
          "channels": ["string"],
          "positioning": "string",
          "summary": "string"
        }""",
        goal
    )
    return {"Marketing": safe_json_parse(reply)}


async def finance_agent(goal):
    print("\n💰 Finance Agent working...")
    reply = call_llm(
        """Return ONLY JSON:
        {
          "budget_split": {"marketing":0,"production":0,"others":0},
          "expected_roi": "string",
          "risk_level": "Low/Medium/High",
          "summary": "string"
        }""",
        goal
    )
    return {"Finance": safe_json_parse(reply)}


async def operations_agent(goal):
    print("\n🏭 Operations Agent working...")
    reply = call_llm(
        """Return ONLY JSON:
        {
          "production_plan": "string",
          "supply_chain": "string",
          "risks": "string",
          "summary": "string"
        }""",
        goal
    )
    return {"Operations": safe_json_parse(reply)}


async def legal_agent(goal):
    print("\n👩‍⚖️ Legal Agent working...")
    reply = call_llm(
        """Return ONLY JSON:
        {
          "compliance": "string",
          "contracts": "string",
          "risk_level": "Low/Medium/High",
          "summary": "string"
        }""",
        goal
    )
    return {"Legal": safe_json_parse(reply)}


async def hr_agent(goal):
    print("\n👩‍💼 HR Agent working...")
    reply = call_llm(
        """Return ONLY JSON:
        {
          "hiring_plan": "string",
          "training_plan": "string",
          "headcount": number,
          "summary": "string"
        }""",
        goal
    )
    return {"HR": safe_json_parse(reply)}


# ================================
# BROADCAST (CORE CONCEPT)
# ================================
async def broadcast(goal):
    print("\n📢 Coordinator Broadcast:")
    print(f"→ {goal}")

    results = await asyncio.gather(
        marketing_agent(goal),
        finance_agent(goal),
        operations_agent(goal),
        legal_agent(goal),
        hr_agent(goal)
    )

    return results


# ================================
# DECISION AGENT
# ================================
def decision_agent(responses):
    final_plan = {}

    for response in responses:
        final_plan.update(response)

    print("\n🧑‍⚖️ Final Corporate Launch Plan:\n")

    for dept, data in final_plan.items():
        print(f"📌 {dept}")
        print(f"   → {data.get('summary', 'No summary')}")

    return final_plan


# ================================
# MAIN SYSTEM
# ================================
async def run_system(goal):
    print("\n🚀 CORPORATE PRODUCT LAUNCH SYSTEM")

    # Step 1: Broadcast
    responses = await broadcast(goal)

    # Step 2: Decision Making
    final_plan = decision_agent(responses)

    return final_plan


# ================================
# RUN
# ================================
goal = "Product X launch in Q3, target market North America, budget $5M."

await run_system(goal)



