# -*- coding: utf-8 -*-
"""multi-agent_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eaMZjRrmez7WG7_db5h9mWGy_fjC2Bck
"""

from google.colab import userdata
api_key = userdata.get('gapi')

import os
from openai import OpenAI
from google.colab import userdata

# ================================
# 🔐 LLM SETUP (COLAB SECRETS)
# ================================
api_key = userdata.get('gapi')

if not api_key:
    raise ValueError("❌ GROQ_API_KEY not found")

client = OpenAI(
    api_key=api_key,
    base_url="https://api.groq.com/openai/v1"
)

# ================================
# 🧠 SHARED MEMORY CLASS
# ================================
class SharedMemory:
    def __init__(self):
        self.data = {}

    def update(self, agent_name, result):
        self.data[agent_name] = result

    def get(self, key):
        return self.data.get(key, "")

    def get_all(self):
        return self.data


# ================================
# 🦾 LLM CALL FUNCTION
# ================================
def call_llm(role, message, temperature=0.4):
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": role},
                {"role": "user", "content": message}
            ],
            temperature=temperature
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        print("❌ LLM Error:", e)
        return "Error"


# ================================
# 🔎 SEARCH AGENT
# ================================
class SearchAgent:
    name = "search"

    def run(self, goal, memory):
        print("\n[Search Agent] Gathering EV data...")

        prompt = f"""
        Goal: {goal}

        Provide key data points about EV industry in India:
        - Market size
        - Growth trends
        - Major companies
        - Government policies
        """

        result = call_llm(
            "You are a research assistant. Provide factual EV data.",
            prompt
        )

        return result


# ================================
# 📊 ANALYST AGENT
# ================================
class AnalystAgent:
    name = "analyst"

    def run(self, goal, memory):
        print("\n[Analyst Agent] Analyzing data...")

        search_data = memory.get("search")

        prompt = f"""
        Analyze the following EV data:

        {search_data}

        Provide insights:
        - Trends
        - Opportunities
        - Risks
        """

        result = call_llm(
            "You are a business analyst. Interpret and summarize insights.",
            prompt
        )

        return result


# ================================
# ✍️ WRITER AGENT
# ================================
class WriterAgent:
    name = "writer"

    def run(self, goal, memory):
        print("\n[Writer Agent] Writing report...")

        analyst_data = memory.get("analyst")

        prompt = f"""
        Write a professional market report on:

        {goal}

        Based on:
        {analyst_data}

        Structure:
        - Introduction
        - Market Overview
        - Trends
        - Conclusion
        """

        result = call_llm(
            "You are a professional report writer.",
            prompt
        )

        return result


# ================================
# ✅ QA AGENT WITH QUALITY THRESHOLD + USER RATING
# ================================
class QAAgent:
    name = "qa"

    def __init__(self, threshold=7, ask_user=True):
        self.threshold = threshold  # Minimum acceptable score (1–10 scale)
        self.ask_user = ask_user    # Option to ask user for rating

    def run(self, goal, memory):
        print("\n[QA Agent] Reviewing report...")

        report = memory.get("writer")

        prompt = f"""
        Review the following report:

        {report}

        Evaluate on:
        - Accuracy
        - Clarity
        - Tone
        - Completeness
        - Coherence
        - Grammar and Spelling
        - Relevance to Goal

        Provide:
        1. A score from 1–10 (overall quality).
        2. Specific improvements if score < {self.threshold}.
        3. A revised version if improvements are needed.
        """

        result = call_llm(
            "You are a QA expert. Score and improve the report.",
            prompt
        )

        score = self._extract_score(result)

        if self.ask_user:
            print("\n📊 QA Agent suggests this report scored:", score)
            print("📄 Report Preview:\n")
            print(report)
            try:
                user_score = int(input("\n👉 Please rate the report yourself (1–10): "))
            except:
                user_score = score

            if user_score < self.threshold:
                print(f"⚠️ You rated {user_score}/10, below threshold {self.threshold}. Refining...")
                return result
            else:
                print(f"✅ You rated {user_score}/10, meets threshold.")
                return report
        else:
            if score < self.threshold:
                print(f"⚠️ Report scored {score}/10, below threshold {self.threshold}. Refining...")
                return result
            else:
                print(f"✅ Report scored {score}/10, meets threshold.")
                return report

    def _extract_score(self, text):
        """Try to extract a numeric score from the LLM output."""
        for token in text.split():
            if token.isdigit():
                return int(token)
        return self.threshold  # fallback if parsing fails


# ================================
# 🧠 ORCHESTRATOR
# ================================
def orchestrator(goal):
    print("=== AI Research Team Pipeline ===")

    # Initialize agents
    agents = [
        SearchAgent(),
        AnalystAgent(),
        WriterAgent(),
        QAAgent(threshold=7, ask_user=True)  # User rating enabled
    ]

    # Shared memory
    memory = SharedMemory()

    # Run pipeline
    for agent in agents:
        result = agent.run(goal, memory)
        memory.update(agent.name, result)

    # Final output
    final_report = memory.get("qa")

    return final_report


# ================================
# 🚀 RUN SYSTEM
# ================================
if __name__ == "__main__":
    goal = "Write a comprehensive market report on EV industry trends in India for 2025."

    report = orchestrator(goal)

    print("\n===============================")
    print("📄 FINAL REPORT:\n")
    print(report)
    print("===============================")

